### ISSUE TITLE
Implement user endpoint in user management page

### ISSUE THREAD

**Issue by leo-hsk** [fra-uas-project/softDsim#151]
### As a super user I want to have an overview over all users in the user overview page and want to be able to delete them.

implement user api
-> DELETE
-> GET

**Comment by antonroesler** [comment]
Sollte das im Studio sein oder eine extra page?

**Comment by leo-hsk** [comment]
@antonroesler das wird eine extra page. Hat nichts mit dem Scenario Studio zutun
