### ISSUE TITLE
Bug: Tasks not updating after first next request with members

### ISSUE THREAD

**Issue by leo-hsk** [fra-uas-project/softDsim#475]
#### Environment 
[ ] Local - Operating system: Win | Python Version: 3.x
[ ] local - Date and time: 01.07.2022

#### Steps to reproduce the issue

1.  Start simulation and select skilltypes (does not matter which)
2. Hit next button

#### What's the expected result? What do you think should happen?

- Tasks going down 

#### What's the actual result? What happened?

- Task remain undone

#### Additional details / screenshot

Only when hitting next the first time. 
Members are sent in request and budget updates as it should.

![image](https://user-images.githubusercontent.com/52975667/176871733-962dbc19-d0de-45c8-97e7-230992bcf1a4.png)

Request: 
![image](https://user-images.githubusercontent.com/52975667/176871814-f36b534d-beb9-46bf-ac8c-e28cd0b547ed.png)
{
    "scenario_id": 322,
    "type": "SIMULATION",
    "actions": {
        "bugfix": false,
        "unittest": false,
        "integrationtest": false,
        "meetings": 0,
        "teamevent": false,
        "training": 0,
        "salary": 1,
        "overtime": 0
    },
    "members": [
        {
            "skill_type": "senior",
            "change": 4
        },
        {
            "skill_type": "junior",
            "change": 0
        },
        {
            "skill_type": "mid",
            "change": 0
        }
    ]
}

Response:
{"type":"SIMULATION","management":{"budget":1000000.0,"duration":100,"tasks":1000},"state":{"component_counter":2,"step_counter":3,"day":5,"cost":100000.0,"budget":1000000,"total_tasks":1000},"tasks":{"tasks_todo":1000,"tasks_done":0,"tasks_unit_tested":0,"tasks_integration_tested":0,"tasks_bug":0},"members":[{"id":454,"motivation":0.75,"familiarity":0.0,"stress":0.1,"xp":0.0,"skill_type":{"id":1,"name":"senior"}},{"id":455,"motivation":0.75,"familiarity":0.0,"stress":0.1,"xp":0.0,"skill_type":{"id":1,"name":"senior"}},{"id":456,"motivation":0.75,"familiarity":0.0,"stress":0.1,"xp":0.0,"skill_type":{"id":1,"name":"senior"}},{"id":457,"motivation":0.75,"familiarity":0.0,"stress":0.1,"xp":0.0,"skill_type":{"id":1,"name":"senior"}}],"team":{"motivation":0.8143499999999995,"familiarity":0.0,"stress":0.155},"text":"# This is the story of the sim frag","actions":[{"action":"bugfix","lower_limit":null,"upper_limit":null},{"action":"unittest","lower_limit":null,"upper_limit":null},{"action":"integrationtest","lower_limit":null,"upper_limit":null},{"action":"meetings","lower_limit":0,"upper_limit":10},{"action":"teamevent","lower_limit":null,"upper_limit":null},{"action":"training","lower_limit":0,"upper_limit":10},{"action":"salary","lower_limit":null,"upper_limit":null},{"action":"overtime","lower_limit":null,"upper_limit":null}]}

**Comment by antonroesler** [comment]
Das sollte jetzt gehen. Da gab es einen Bug das alles eine Woche verzögert war, mit #479 wurde das gelöst.
