### ISSUE TITLE
Add options to register as staff or admin user

### ISSUE THREAD

**Issue by phimer** [fra-uas-project/softDsim#99]

**Comment by antonroesler** [comment]
Wie können wir diesen Endpunkt in Zukunft sichern? Am Ende ist wahrscheinlich die einzige Möglichkeit, dass man sich nur als normaler User registrieren kann und nur Admins über die Userverwaltung andere User zu Admins machen können. In dem Fall würden wir den Endpoint eigentlich gar nicht brauchen.
